// <auto-generated />
using System;
using Assistant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assistant.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310182729_RenameDeferredIntents")]
    partial class RenameDeferredIntents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Api.Domain.Entities.AssistantPersonality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonalityText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("personality_text");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("assistant_personalities", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.DeferredIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("text")
                        .HasColumnName("execution_result");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hangfire_job_id");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<string>("OriginalInstruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_instruction");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .IsUnique();

                    b.HasIndex("ChatId", "Status");

                    b.ToTable("deferred_intents", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("BillingPeriodEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_end_date");

                    b.Property<DateTime>("BillingPeriodStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_period_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<string>("HangfireJobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at_utc");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_id");

                    b.Property<DateTime?>("RunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<long?>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId")
                        .IsUnique();

                    b.HasIndex("ChatId", "Status");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("telegram_users", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.UserMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("user_memories", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.AssistantPersonality", b =>
                {
                    b.HasOne("Assistant.Api.Domain.Entities.TelegramUser", "TelegramUser")
                        .WithOne("AssistantPersonality")
                        .HasForeignKey("Assistant.Api.Domain.Entities.AssistantPersonality", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Assistant.Api.Domain.Entities.TelegramUser", "TelegramUser")
                        .WithMany("Expenses")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.UserMemory", b =>
                {
                    b.HasOne("Assistant.Api.Domain.Entities.TelegramUser", "TelegramUser")
                        .WithMany("Memories")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Domain.Entities.TelegramUser", b =>
                {
                    b.Navigation("AssistantPersonality");

                    b.Navigation("Expenses");

                    b.Navigation("Memories");
                });
#pragma warning restore 612, 618
        }
    }
}
