// <auto-generated />
using System;
using Assistant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Assistant.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261002214038_AddAgentEmotionState")]
    partial class AddAgentEmotionState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.AgentEmotionState", b =>
                {
                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<double>("Arousal")
                        .HasColumnType("double precision")
                        .HasColumnName("arousal");

                    b.Property<int?>("LastTurnId")
                        .HasColumnType("integer")
                        .HasColumnName("last_turn_id");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("mood");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("Valence")
                        .HasColumnType("double precision")
                        .HasColumnName("valence");

                    b.HasKey("TelegramUserId");

                    b.ToTable("agent_emotion_states", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.ChatTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssistantMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assistant_message");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTime?>("MemoryProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("memory_processed_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "UserMessage", "AssistantMessage" });

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_message");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_chat_turns_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TelegramUserId", "CreatedAt")
                        .HasDatabaseName("IX_chat_turns_telegram_user_id_created_at");

                    b.ToTable("chat_turns", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.DeferredIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cron_expression");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("text")
                        .HasColumnName("execution_result");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hangfire_job_id");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<string>("OriginalInstruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_instruction");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .IsUnique();

                    b.HasIndex("ChatId", "Status");

                    b.ToTable("deferred_intents", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.StoredAgentSession", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("session");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChatId");

                    b.ToTable("agent_sessions", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.AssistantPersonality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonalityText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("personality_text");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("assistant_personalities", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("telegram_users", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryConsolidationState", b =>
                {
                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<bool>("IsJobQueued")
                        .HasColumnType("boolean")
                        .HasColumnName("is_job_queued");

                    b.Property<DateTime?>("JobQueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("job_queued_at_utc");

                    b.Property<DateTime?>("JobStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("job_started_at_utc");

                    b.Property<DateTime?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at_utc");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<int>("LastConsolidatedChatTurnId")
                        .HasColumnType("integer")
                        .HasColumnName("last_consolidated_chat_turn_id");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.HasKey("TelegramUserId");

                    b.ToTable("user_memory_consolidation_states", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_core");

                    b.Property<DateTime>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.PrimitiveCollection<int[]>("SourceTurnIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("source_turn_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("integer")
                        .HasColumnName("superseded_by_id");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SupersededById");

                    b.HasIndex("TelegramUserId", "Status")
                        .HasDatabaseName("IX_user_memory_items_telegram_user_id_status");

                    b.ToTable("user_memory_items", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryManifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TelegramUserId", "IsActive")
                        .HasDatabaseName("IX_user_memory_manifests_telegram_user_id_is_active");

                    b.ToTable("user_memory_manifests", (string)null);
                });

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.AgentEmotionState", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithOne()
                        .HasForeignKey("Assistant.Api.Features.Chat.Models.AgentEmotionState", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.Chat.Models.ChatTurn", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithMany("ChatTurns")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.AssistantPersonality", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithOne("AssistantPersonality")
                        .HasForeignKey("Assistant.Api.Features.UserManagement.Models.AssistantPersonality", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryConsolidationState", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithOne("MemoryConsolidationState")
                        .HasForeignKey("Assistant.Api.Features.UserManagement.Models.UserMemoryConsolidationState", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryItem", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.UserMemoryItem", "SupersededBy")
                        .WithMany()
                        .HasForeignKey("SupersededById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupersededBy");

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.UserMemoryManifest", b =>
                {
                    b.HasOne("Assistant.Api.Features.UserManagement.Models.TelegramUser", "TelegramUser")
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Assistant.Api.Features.UserManagement.Models.TelegramUser", b =>
                {
                    b.Navigation("AssistantPersonality");

                    b.Navigation("ChatTurns");

                    b.Navigation("MemoryConsolidationState");
                });
#pragma warning restore 612, 618
        }
    }
}
